version: "2"
services:
  app:
    extends:
      file: docker-compose.yml
      service: app
    volumes:
      - ./request-logs:/usr/app/request-logs
      - ./server-logs:/usr/app/server-logs
      - ./src:/usr/app/src:ro
      - ./yarn.lock:/usr/app/yarn.lock
    links:
      - db
    command: 'sh -c "cat /tmp/yarn.lock > yarn.lock && yarn watch"'

  db:
    extends:
      file: docker-compose.yml
      service: db

  db-seed:
    extends:
      file: docker-compose.yml
      service: db-seed
    links:
      - db
